### ISSUE TITLE
WZTOE_WebServer Link Off

### ISSUE THREAD

**Issue by vervaekejonathan** [Wiznet/W7500x_StdPeriph_Lib#1]
Hi,
I'm trying the WZTOE_WebServer example on W7500P with eclipse gcc 4.8q1 on a linux host.

When running the code I get this:

> W7500x Standard Peripheral Library version : 1.0.0
> SourceClock : 8000000
> SystemClock : 8000000
> PHY Init : Success
> Link : Off
> MAC: 00:08:DC:01:02:03
> IP: 0.0.0.0
> GW: 0.0.0.0
> SN: 0.0.0.0
> DNS: 0.0.0.0
> Start DHCP

Link is Off and DHCP never happens.
Why is the link off and how can I fix this so that DHCP works?

Thanks!

**Comment by bjnhur** [comment]
Hi~ I test again with W7500P board and also get the same problem like you. 
I will review the code, but need some time~.
I'll let you know if I have any updates.
Thanks~

**Comment by vervaekejonathan** [comment]
That's great news, thanks!

**Comment by Ricky-Kwon** [comment]
Did you check below?

> Select the target product to be used, comment/uncomment the right define:
/* Uncomment the line below according to the target W7500x device used in your
 application
 */
#if !defined (W7500) && !defined (W7500P)
//#define W7500
#define W7500P
#endif

**Comment by vervaekejonathan** [comment]
yes i've changed that file, and also the board in main.h to #define USE_WIZWIKI_W7500P_EVAL

**Comment by bjnhur** [comment]
I fixed some bugs in GPIO function. please update the fix. 
https://github.com/Wiznet/W7500x_StdPeriph_Lib/commit/15d0d2bd3f0b369a8c8aab346c258879e6df0d97

Good luck to you!!

**Comment by Ricky-Kwon** [comment]
OMG

**Comment by Ricky-Kwon** [comment]
Anyway, did you have to remain it like this?

```
/* fix bug 2019.05.03 */
//(GPIOx->LB_MASKED[(uint8_t) (GPIO_Pin)]) = GPIO_Pin;
//(GPIOx->UB_MASKED[(uint8_t) ((GPIO_Pin) >> 8)]) = GPIO_Pin;
```


Change history is managed by git. LOL

**Comment by vervaekejonathan** [comment]
It does not seem to work. When I'm trying, it hangs on the  ` while (!PHY_GetLinkStatus()) ; ` function.

**Comment by vervaekejonathan** [comment]
in the main function, the following GPIO's are set:

```
#ifdef W7500
    printf("PHY Init : %s\r\n", PHY_Init(GPIOB, GPIO_Pin_15, GPIO_Pin_14) == SET ? "Success" : "Fail");
#elif defined (W7500P)
    printf("PHY Init : %s\r\n", PHY_Init(GPIOB, GPIO_Pin_14, GPIO_Pin_15) == SET ? "Success" : "Fail");
#endif
```
These are the parameters for PHY_Init

`
FlagStatus PHY_Init(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin_MDC, uint16_t GPIO_Pin_MDIO)
`
From the datasheet, I see for an W7500X device MDC is on PB_15 and MDIO is on PB_14.
Why is this change required for W7500P? When switching these 2 pins around, I get the folllowing feedback:

```
W7500x Standard Peripheral Library version : 1.0.0
SourceClock : 8000000
SystemClock : 8000000
PHY Init : Fail
Link : On
Link is OK
MAC: 00:08:DC:01:02:03
IP: 0.0.0.0
GW: 0.0.0.0
SN: 0.0.0.0
DNS: 0.0.0.0
Start DHCP
```

Seems like the link is OK now, but the PHY fails.

**Comment by vervaekejonathan** [comment]
More info:
The important part seems to be MDIO_GetData()

When checking the PHY, the following code is executed (i've added some logging):

```
    for (i = 0; i < 8; i++) {
        data = MDIO_GetData(i, PHYREG_STATUS);
        printf("PYH_GetID %i\r\n", data);
```
When Checking the Link status, I've added this:

` printf("PHY_GetLinkStatus %i\r\n", MDIO_GetData(PHY_ADDR, PHYREG_STATUS)); `

This is the result:

```
PYH_GetID 65535
PYH_GetID 65535
PYH_GetID 30793
PHY Init : Success
PHY_GetLinkStatus 30793
Link : Off
```

Seems like the following bit is not set in the GetLinkStatus result: PHYREG_STATUS_LINK

How can I have more information on the PHYREG_CONTROL register? This way I could debug better.

**Comment by vervaekejonathan** [comment]
I'm trying to compare the mbed implementation (W7500x_toe.cpp) with this implementation

I notice the same code:
```
void mdio_write(GPIO_TypeDef* GPIOx, uint32_t PhyRegAddr, uint32_t val)
{
    output_MDIO(GPIOx, 0xFFFFFFFF, 32);
    output_MDIO(GPIOx, 0x05, 4);
    output_MDIO(GPIOx, PHY_ADDR, 5);
    output_MDIO(GPIOx, PhyRegAddr, 5);
    output_MDIO(GPIOx, 0x02, 2);
    output_MDIO(GPIOx, val, 16);
    idle_MDIO(GPIOx);
}
```
and 

``` 
static void MDIO_SetData(uint32_t regAddr, uint32_t val)
{
    /* 32 Consecutive ones on MDO to establish sync */
    MDIO_Out(0xFFFFFFFF, 32);

    /* start code 01, write command (01) */
    MDIO_Out(0x05, 4);

    /* write PHY address */
    MDIO_Out(PHY_ADDR, 5);

    MDIO_Out(regAddr, 5);

    /* turnaround MDO */
    MDIO_Out(0x02, 2);

    /* Write the data value */
    MDIO_Out(val, 16);

    /* turnaround MDO is tristated */
    MDIO_Idle();
}
```
But... in mbed, PHY_ADDR is set to 0x01 and this repo, 0x02 is found as the ID during `PHY_GetId()`

This confuses me...

**Comment by vervaekejonathan** [comment]
I got it working by disabling the following code:

```
#elif defined (W7500P)
    /*GPIO_PinPadConfig(GPIOB, GPIO_PinSource12, GPIO_PuPd_UP|GPIO_InputBufferEnable|GPIO_CMOS);
    GPIO_PinAFConfig(GPIOB, GPIO_PinSource5, PAD_AF1);
    GPIO_PinPadConfig(GPIOB, GPIO_PinSource5, GPIO_PuPd_UP|GPIO_InputBufferEnable|GPIO_CMOS);
    GPIO_PinAFConfig(GPIOB, GPIO_PinSource6, PAD_AF1);
    GPIO_PinPadConfig(GPIOB, GPIO_PinSource6, GPIO_PuPd_UP|GPIO_InputBufferEnable|GPIO_CMOS);

    GPIO_PinAFConfig(GPIOD, GPIO_PinSource6, PAD_AF1);
    GPIO_PinPadConfig(GPIOD, GPIO_PinSource6, GPIO_PuPd_DOWN);
    GPIOD->OUTENSET = GPIO_Pin_6;
    GPIO_SetBits(GPIOD, GPIO_Pin_6);*/
#endif
```

Any advice or feedback on this?
Is there a way to see how the routing happens between the W7500 and the internal PHY so these pins can be checked?

**Comment by bjnhur** [comment]
I checked again and had a few changes.
please update the following commit in your codes.

https://github.com/Wiznet/W7500x_StdPeriph_Lib/commit/e28ead15b31bd390574b9bcf3496200c22facf21

Good luck again~~

PS) for the PHY ID, you must call the PHY_GetId() function to get real PHY ID(ADDR), because W7500P don't assign fixed PHYID(ADDR) in the production.

**Comment by vervaekejonathan** [comment]
It works! Thanks!
