### ISSUE TITLE
I2C support

### ISSUE THREAD

**Issue by vervaekejonathan** [Wiznet/W7500x_StdPeriph_Lib#3]
Is I2C supported in the library? Which library should I use and is an example available?
Thanks!

**Comment by irinakim12** [comment]
Hi~ You can use the attached file of below.

[W7500_I2c.zip](https://github.com/Wiznet/W7500x_StdPeriph_Lib/files/3159781/W7500_I2c.zip)

Thanks
BR
iria

**Comment by vervaekejonathan** [comment]
Required some rewrites on the GPIO initialization to be compatible with this repo, but it compiles now. Will test later if it works. Thanks!

**Comment by bjnhur** [comment]
For your reference, we added i2c examples using GPIO into W7500x_StdPeriph_Lib/Projects/W7500x_StdPeriph_Examples/GPIO.
Enjoy your project!

**Comment by vervaekejonathan** [comment]
confirming I2C works!
