### ISSUE TITLE
Receive multicast UDP message

### ISSUE THREAD

**Issue by vervaekejonathan** [Wiznet/W7500x_StdPeriph_Lib#8]
Hi,
I'm trying to receive a multicast packet, send to ip 235.255.255.250 on port 1900

This is my relevant code:

```
socket(sn, Sn_MR_UDP, port, SF_MULTI_ENABLE )
while(1)
{
    if ((size = getSn_RX_RSR(sn)) > 0) {
        uint8_t ip[4];
        uint16_t port;
        if (size > DATA_BUF_SIZE) size = DATA_BUF_SIZE;
        ret = recvfrom(sn, buf, size, ip, &port);
        printf("> Receive DNS message from %d.%d.%d.%d(%d). len = %d\r\n", ip[0], ip[1], ip[2], ip[3],port,size);
        if (ret <= 0) return ret;
        buf[size] = "\0";
        printf("%s", buf);
    }
}

```
But I only receive messages directly send to the IP of the device. So no messages send to 235.255.255.250 are received.

Any ideas?
Thanks!

**Comment by irinakim12** [comment]
Hi~
Thank you for writing, let me test about UDP multicast.

First, could you please let me know about your network environment?
 1. such as Network configuration diagram  ....etc...

thanks
BR
irina

**Comment by irinakim12** [comment]
@vervaekejonathan 
Hi~

**Comment by irinakim12** [comment]
Hi~
I uploaded the UDP multicasting example in WZTOE folder.
Please check the code again

thanks,
BR
irina

**Comment by vervaekejonathan** [comment]
Ok thanks!
